<%@ Page Title="" Language="C#" MasterPageFile="Blog.master" AutoEventWireup="true" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ListsAndJournalContentPlaceHolder" runat="Server">
    <h2>When a country bled blue!</h2>
    <br />


    <p>
        've been trying to write this blog down, ever since Team India lifted the ICC World Cup on April 2nd 2011. Ultimately, grabbed sometime to do it. I've been an avid cricket fan from my childhood and I still bear in mind, the moments of the 1992 cricket world cup, which I suppose is the very first cricket competition, I comprehended and enjoyed, watching as a young boy at ten, chiefly the semi final match. It was the legend Sachin Ramesh Tendulkar, who without much pretence invoked my craze for cricket. But, it was the 1996 World cup that I followed with all my might, but only to finish, with an unacceptable semi final for Team India. 
    </p>
    <p>
        I've had chances to watch the good ol' 1983 matches on the idiot box and they seemed glorious, immaculate moments. Even being a great fan of the Indian cricket team, I never had the complete assurance in them to lift the prestigious golden trophy. My interest towards cricket vaguely faltered, when the match fixing scandals surfaced. But then it was impermanent. For me, Team India had the only chance to win a World Cup, when the formidable 2003 team, blazed into the finals. It was quite a deep, profound team with all round performance. Saurav, Sachin, Dravid, seemed like they were destined to lift the cup. But the truth was far more heart breaking. Even such a good team, stood as a pile of nothing against Ponting's mammoth men. And that was the first day; I held back my thoughts of India ever winning a cricket world cup again.
    </p>
    <p>
        It has been raining cricket for Team India, ever after Dhoni was capped in. IPLs, International T20 World Cups and now ICC cricket World Cup 2011. Although, there was a premeditated hype, on India being the strongest contender for the cup, nothing did help boost my confidence over them. But yes, I wanted them to (as always). I did not get to watch the opening match of the world cup between India and Bangladesh from top to bottom. But it was a no surprise match, unlike the disgustingly hard earned wins against Netherlands and super wooing Ireland. The thriller against England was a extravagant watch that landed up in a tie. I enjoyed it. But then the match with South Africa, where we choked for a disparity, was a touch unsatisfactory.
        <br />
    </p>
    <p>
        The quarter finals with Australia had me in. It was a great match. I was stuck to my sofa, but when the captain was dismissed, I went almost crazy, but then stupendous work from Raina and Yuvraj saw us through. The semi final for me was more like watching a movie, where in I thought the players played as if they were actors. If you know what I mean. But, I have to admit that I enjoyed that too.
    </p>
    <p>
        But then, the Saturday, Apr 02, 2011 was much more than just a memorable game. It was the final of the World Cup 2011, wherein two sub continental nations play in the finals for the first time. The cricket frenzy nation was roaring all the way. I sat down to watch the match, just missing the toss, which heard had come hullabaloo. I was the only person watching the match at home, when the team from the adjacent island was batting first. It was an interesting start. I've never seen India field so well; Raina and Yuvraj, inarguably the best fielders in the team, were electrifying. The bowling was above Indian standards in the first few overs. But then, credits to Jayewardene and Sangakkara, who played gracious knocks, to settle the team for a defendable total. Also, credits to Perrara towards the final over. (Or should I thank Zaheer Khan??).
    </p>
    <p>
        Much more fascinating part was, when the host batted second. Just before the innings began, I went to a temple. For the people who over assume, the reason for me visiting the temple was just one of my usual visits on Saturday. But then, while I was on my way back, the Indian innings had already started and all I can see was deserted streets, empty alleys with dim lights.  But out of the blue, there was a perpetual increase in the number of people around the corners and roads. I inadvertently and faintly overheard two guys speaking over near the shops. One was saying "Sachin is Out!". The other in reply,"I thought it was only Sehwag". By the end of the conversation, I knew both Sachin and Sehwag were out and back in the dressing room, which explained me the boost in the mass on the roads. Nevertheless, I was disenchanted too. The situation was pretty similar to that of the 2003 World Cup final; only the target was easier this time around. When I reached home, it was two down with Kohli and Gambhir knocking the ball around of ones and twos. I had to go out again. I returned only to find Dhoni in the crease. Alas! Kohli was gone too. Began watching the match full fledged. Along with me was my "<em>paati</em>" (Granny). She even got a headache with the tension. I was persistently being messaged by my wife, who was not in at home. There was slow build up of tension, levelled by a few moments of relaxation with the perfected shots from MSD and Gambhir. The six from the upper cut, from the captain, was out of this world. For every shot that flew over or rolled to the boundary, I could hear screams from the locality. Towards the end, it was easier to predict India win and when, four was required in the penultimate over for the Indians to lift the monster, MSD flung the bat, with all the power from his back hand, which came into play at the ecstatic moment of the whole country plunging from the seats with sheer joy and whole hearted mental leap, for a huge six. The neighbourhood was celebrating, fireworks all over, cell phone networks jammed, no calls were going out and so were the messages. At last received message from my wife and call from my friend Kanda. It was congratulations all around. The presentation and carnival ceremonies with Sachin on the shoulders were incredible and when Kohli commented "He has been carrying around the team and nations burden on his shoulders for 21 years, now its time that we do it for him", I just had what they call "cutis anserine".
    </p>
    <p>
        Be it just a game, or a game that was fixed, or a waste of time, as a few might describe it, but for me, the cricket world cup final was just sheer entertainment. It was thrilling. It is as if we had our life over it for a while. Ain't that the reason, we go for a roller coater ride.<br />
    </p>
</asp:Content>

